# -*- mode: ruby -*-
# vi: set ft=ruby :

# Docs: https://www.vagrantup.com/
SSH_USERNAME = 'ubuntu'
SSH_KEY_PATH = '~/.ssh/cloud-benchmarking.pem'
VAGRANTFILE_API_VERSION = '2'
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.hostname = 'wordpress-berkshelf'

  if Vagrant.has_plugin?('vagrant-omnibus')
    config.omnibus.chef_version = '12.8.1'
  else
    fail "Vagrant-omnibus plugin not installed. Please install the plugin via\n
            `vagrant plugin install vagrant-omnibus` before continuing."
  end

  config.vm.box = 'aws'
  config.vm.box_url = 'https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box'

  config.ssh.username = SSH_USERNAME
  config.ssh.private_key_path = SSH_KEY_PATH

  config.vm.provider :aws do |aws, override|
    aws.access_key_id = ENV['AWS_ACCESS_KEY_ID']
    aws.secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']

    aws.keypair_name = 'cloud-benchmarking'
    aws.region = 'eu-west-1'
    aws.availability_zone = 'eu-west-1a'
    # Official Ubuntu 14.04 LTS (hvm:ebs) image for eu-west-1 from Canonical:
    #  https://cloud-images.ubuntu.com/locator/ec2/
    aws.ami = 'ami-acb59bdf'
    aws.instance_type = 't2.micro'
    # # Make sure HTTP port is open!
    aws.security_groups = ['cwb-web']
    aws.tags = { 'Name' => 'wordpress' }
  end

  config.berkshelf.enabled = true
  config.berkshelf.berksfile_path = "../Berksfile"

  config.vm.provision :chef_solo do |chef|
    chef.run_list = [
      'recipe[apt]',
      'recipe[wordpress::setup]'
    ]

    chef.json = {
      wordpress: {
        version: '4.7.1', # or 'latest'
        site: {
          # url: "http://HOSTNAME"
        },
        plugins: {
          # https://wordpress.org/plugins/disable-check-comment-flood/installation/
          # disable_check_comment_flood: 'disable-check-comment-flood',
          # https://github.com/bordoni/fakerpress
          # fakerpress: 'https://github.com/bordoni/fakerpress/archive/0.3.1.zip'
        }
      }
    }
  end
end
